require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'capybara'
require 'capybara/dsl'
require 'selenium-webdriver'
require 'cgi'
require 'timeout'

# require_relative '../lib/course_ripper/scraper'
# require_relative '../lib/course_ripper/library'
# require_relative '../lib/course_ripper/library_details'
# require_relative '../lib/course_ripper/cli'
