require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'capybara'
require 'capybara/dsl'
require 'selenium-webdriver'
require 'cgi'
require 'timeout'

require_relative '../lib/course_ripper/ripper'
require_relative '../lib/course_ripper/cli'
